### PR TITLE
Add postgres install step to docker.md

### PR DESCRIPTION
**Pull request by ohrely**

### CODE REVIEW

**Comment by amleung21** [comment]
You don't actually need to install postgres locally for the docker method to work. I should have added more clarification to the "Stop local instances of postgres" step. That's only necessary if you happen to already have installed it locally and you want to make sure when you run 'psql' that it's attaching to the docker container, not the locally running instance of postgres. I'll  add more clarification to that step.

**Comment by ohrely** [comment]
I tried running without postgres installed, but `psql -U postgres -h localhost` didn't work without the local install.  Smooth sailing otherwise.

**Comment by amleung21** [comment]
Ah! I guess you need the 'psql' command itself. Maybe there's a way to get just that...

**Comment by amleung21** [comment]
A quick search didn't turn up anything for a client-only install. Merging...

**Pull request merged**
